# Site settings
title: Tray OpenCode
email: rsantos@tray.com.br
description: > # this means to ignore newlines until "baseurl:"
  Galeria de componentes OpenCode da plataforma de e-commerce Tray
baseurl: "/opencode-components" # the subpath of your site, e.g. /blog/
url: "http://tray-tecnologia.github.io/opencode-components" # the base hostname & protocol for your site
excerpt_separator: https://github.com/mojombo/jekyll/issues/1401

# Build settings
markdown: kramdown
